name: Alternaive

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@ci-workflow
    secrets:
      nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
