name: Alternaive

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v14
    secrets:
      nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
      access-tokens: github.com=${{ secrets.SVADIL_TOKEN }}
    with:
      nix_conf: access-tokens = github.com=${{ secrets.access-tokens }}
