name: Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checks:
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v19
    secrets:
      nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
